### ISSUE TITLE
App crash on setupPlayer() due to ExoPlayer conflict from react-native-video 

### ISSUE THREAD

**Issue by djmMax** [react-native-kit/react-native-track-player#267]
I added react-native-track-player:0.2.5 and react-native-video:3.2.0
TrackPlayer use exoplayer r2.4.3 but react-native-video use exoplayer  2.7.3

**Comment by dcvz** [comment]
v1.0.0 should fix this, but otherwise you may have to do some conflict resolution on versions. 

Unfortunately we can't make sure that we work with every other library out there.

**Comment by aLLUPS** [comment]
If somebody is facing this issue still, the only solution is to downgrade `react-native-video` until it matches the **exoplayer versions** of both `react-native-track-player` and `react-native-video`.
Find a more compressive answer here:  [https://stackoverflow.com/a/72048537/12215054](https://stackoverflow.com/a/72048537/12215054)
