### ISSUE TITLE
[Android] Error (crash the app) on log out

### ISSUE THREAD

**Issue by vendicto** [react-native-kit/react-native-track-player#351]
I run app and then just close it, I receive this error: 
```
Process: com.abenogrolig, PID: 23739
    java.lang.RuntimeException: Unable to start service com.guichaguri.trackplayer.service.MusicService@81006c9 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3314)
        at android.app.ActivityThread.-wrap21(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
        at com.guichaguri.trackplayer.service.MusicService.onStartCommand(MusicService.java:53)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3297)
        at android.app.ActivityThread.-wrap21(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
```

this is my json 
```
"version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "run-android": "react-native run-android",
    "buildAndroidRelease": "cd android && ./gradlew assembleRelease"
  },
  "dependencies": {
    "react": "16.6.1",
    "react-native": "0.57.5",
    "react-native-track-player": "^1.0.0",
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.2",
    "react-navigation": "^2.18.2",
    "react-test-renderer": "16.6.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
```
This is build gradle
```
{
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
```
Maybe it helps to resolve the problem.
Seems that in this function I receive the error in intent variable MusicService.java
```
 @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        String action = intent.getAction();
        if (action != null && action.equals("android.intent.action.MEDIA_BUTTON")) {
            MediaButtonReceiver.handleIntent(manager.getMetadata().getSession(), intent);
            return START_NOT_STICKY;
        }

        manager = new MusicManager(this);
        super.onStartCommand(intent, flags, startId);
        return START_STICKY;
    }
```

**Comment by Guichaguri** [comment]
This has been fixed in the `dev` branch.

**Comment by vendicto** [comment]
> This has been fixed in the `dev` branch.

I've changed branch to dev and still have this error.
Could you write down a link for the first issue about this error?

**Comment by Guichaguri** [comment]
Try running `yarn add react-native-kit/react-native-track-player#dev`.
The original issue is #308

**Comment by vendicto** [comment]
Yep, I did it, but the problem didn't disappear. 
I've checked it and notice that my problem is different. I play tracks only from url. 
There are steps:
I didn't play any tracks in app, closed it, and close notification bar, after this steps I've got this error.

**Comment by maendamedia** [comment]
I also get errors on Android with these errors:

> java.lang.RuntimeException: 
>   at android.app.ActivityThread.handleServiceArgs (ActivityThread.java:3821)
>   at android.app.ActivityThread.access$1800 (ActivityThread.java:207)
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1779)
>   at android.os.Handler.dispatchMessage (Handler.java:106)
>   at android.os.Looper.loop (Looper.java:193)
>   at android.app.ActivityThread.main (ActivityThread.java:6863)
>   at java.lang.reflect.Method.invoke (Native Method)
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:537)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
> Caused by: java.lang.NullPointerException: 
>   at com.guichaguri.trackplayer.service.MusicService.onStartCommand (MusicService.java:68)
>   at android.app.ActivityThread.handleServiceArgs (ActivityThread.java:3802)

**Comment by Guichaguri** [comment]
@maendamedia which version are you using?

**Comment by maendamedia** [comment]
This is in package.json

"react-native-track-player": "^1.0.2"

**Comment by Guichaguri** [comment]
d20bd2b6ffe9e96e4ffdcefe5ec08dd6056688c7 should solve the issue.
