### ISSUE TITLE
iOS: Playlist not skipping to next track when complete

### ISSUE THREAD

**Issue by jasongrishkoff** [react-native-kit/react-native-track-player#62]
Seems like the 'playback-track-changed' event just doesn't want to fire, and the playlist doesn't change to the next song -- neither in foreground or background. @dcvz have you tested this on your side?

**Comment by olivierlesnicki** [comment]
+1

**Comment by olivierlesnicki** [comment]
That's because `func audioPlayer(_ audioPlayer: AudioPlayer, didFinishPlaying item: Track) {` is not an existing delegate method:
https://github.com/react-native-kit/react-native-track-player/blob/dev/ios/RNTrackPlayer/Vendor/AudioPlayer/player/AudioPlayerDelegate.swift#L35

**Comment by olivierlesnicki** [comment]
We can replace:

```swift    
    func audioPlayer(_ audioPlayer: AudioPlayer, didFinishPlaying item: Track) {
        if (!playNext()) {
            delegate?.playerExhaustedQueue()
        }
    }
```

with

```swift
    func audioPlayer(_ audioPlayer: AudioPlayer, didUpdateProgressionTo time: TimeInterval, percentageRead: Float) {
        if (percentageRead >= 100) {
            if (!playNext()) {
                delegate?.playerExhaustedQueue()
            }
        }
    }
```

In `Logic/Mediawrapper.swift`

**Comment by jasongrishkoff** [comment]
@olivierlesnicki will test that soon and get back to you to see if it works

**Comment by Guichaguri** [comment]
@olivierlesnicki does that makes `playback-track-changed` and `playback-queue-ended` work properly?

**Comment by dcvz** [comment]
This should be fixed in d28d402e85f3f311bec60f5c0cbdf3f7fb14c211 🚀

**Comment by olivierlesnicki** [comment]
If the plan is to fix it in the vendor we should also create a pull request upstream:
https://github.com/delannoyk/AudioPlayer

**Comment by macci10** [comment]
@dcvz Still not playing tracks when previous is completed. update to 0.2.4.

**Comment by ntk860** [comment]
I am having the same problem

**Comment by jariwalabhavesh** [comment]
I am facing a weird issue skipping to next track when the current track is working fine. But in my case when I am passing 3 tracks array then it will always skip 2nd track and start 3rd track directly. It is only happening in ios. In android it is working fine.

And also in ios, there is a specific case where it happened. If one track is over and automatically it starts playing next track here it is skipping 2nd track and start 3rd one.

But when we manually change track using method `TrackPlayer.skipToNext()` then is playing 2nd track.

I don't know why it is happening when the library automatically changes track.

Here are an example and screenshots. I had loaded 3 track in track player
tracksIds  = ["779/779.mp3","780/780.mp3","781/781.mp3"]

**Here is how on track change event send data when we use `TrackPlayer.skipToNext()`**

When an audio player start playing
{track: null, nextTrack: "779/779.mp3", position: 0}

when I call `TrackPlayer.skipToNext()`
**{track: "779/779.mp3", nextTrack: "780/780.mp3", position: 40.494045174}**

when I again call `TrackPlayer.skipToNext()`
{nextTrack: "781/781.mp3", track: "780/780.mp3", position: 30.435507483}

Here is how on track change event send data when track player automatically changes audio no completion of current Track

When an audio player start playing
{track: null, nextTrack: "779/779.mp3", position: 0}

When track 779.mp3 finishes. I got following data from no track change listener
**{nextTrack: "781/781.mp3", position: 3356.256, track: "780/780.mp3"}**
and when we see it start playing 3rd audio by skipping 2nd track that is 780.

You can see the difference in on data receiving from on track change listener when 1st audio finished and we change with the method.

Any one facing these kind of issue

**Comment by curiousdustin** [comment]
@jariwalabhavesh, this sounds like a different issue from what this thread was about. Can you please make a separate issue? 

Also the screenshots you mentioned didn't seem to get included.

**Comment by jariwalabhavesh** [comment]
@curiousdustin: Thank you for the response I will create a new issue. With screenshot

**Comment by jariwalabhavesh** [comment]
@curiousdustin : looks like fixed in v1.2.3
