### ISSUE TITLE
Events are unreliable, `playback-queue-ended` triggered twice for a single playback session

### ISSUE THREAD

**Issue by sslash** [react-native-kit/react-native-track-player#683]
# Configuration
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 2.65 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.0
        System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.5 => 0.59.5
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

# Issue
## react-native-track-player version: 1.1.8

I want to play a queue of 4 tracks and get notified when each track is finished. I use the event system to get notified, but the `playback-track-changed` event is only triggered at the beginning of the **first 3 tracks**, and the `playback-queue-ended` event is **triggered 2 times**: when the last track starts and when the last track ends. Is this correct behavior? This behavior is not documented and I am reluctant to use this in production. An alternative solution is to just add 1 track at a time to the queue, but then it won't work to play the all the tracks consecutively when the app is in background. Btw, I also add duration to the track objects, as suggested in the docs.

It's not really documented how to deal with this issue, and the events seem unreliable. Any clarification on this issue is very much appreciated. Thanks!

**Comment by matt-dalton** [comment]
+ 1

**Comment by jariwalabhavesh** [comment]
+1

**Comment by hiroyaiizuka** [comment]
We found a solution.

https://stackoverflow.com/questions/39974210/why-componentdidmount-gets-called-multiple-times-in-react-js-redux

move setupPlayer  to App.js

```App.js
async componentDidMount(){
   await TrackPlayer.setupPlayer()
        ・・・
}
```

Hope it will help~

**Comment by HessiPard** [comment]
> # Configuration
> ```
>   React Native Environment Info:
>     System:
>       OS: macOS 10.14.5
>       CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
>       Memory: 2.65 GB / 16.00 GB
>       Shell: 5.3 - /bin/zsh
>     Binaries:
>       Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
>       Yarn: 1.15.2 - ~/.yarn/bin/yarn
>       npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
>       Android SDK:
>         API Levels: 28, 29
>         Build Tools: 28.0.3, 29.0.0
>         System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
>     IDEs:
>       Android Studio: 3.4 AI-183.6156.11.34.5522156
>       Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
>     npmPackages:
>       react: 16.8.3 => 16.8.3
>       react-native: 0.59.5 => 0.59.5
>     npmGlobalPackages:
>       react-native-cli: 2.0.1
> ```
> 
> # Issue
> ## Platform: iOS
> ## react-native-track-player version: 1.1.8
> I want to play a queue of 4 tracks and get notified when each track is finished. I use the event system to get notified, but the `playback-track-changed` event is only triggered at the beginning of the **first 3 tracks**, and the `playback-queue-ended` event is **triggered 2 times**: when the last track starts and when the last track ends. Is this correct behavior? This behavior is not documented and I am reluctant to use this in production. An alternative solution is to just add 1 track at a time to the queue, but then it won't work to play the all the tracks consecutively when the app is in background. Btw, I also add duration to the track objects, as suggested in the docs.
> 
> It's not really documented how to deal with this issue, and the events seem unreliable. Any clarification on this issue is very much appreciated. Thanks!

have this problem too.

**Comment by hery-finimize** [comment]
This [PR](https://github.com/react-native-kit/react-native-track-player/pull/772) should fix `playback-track-changed` not getting called for the last track.

**Comment by curiousdustin** [comment]
https://github.com/react-native-kit/react-native-track-player/commit/fff44d90849e9f0bc53317b32b90c21c4d431551 should resolve this.

**Comment by SolankiYogesh** [comment]
@curiousdustin still facing same issues  queue ended event called multiple time also app got stucked

**Comment by guzeradimaz** [comment]
still actual, help pls
